Update azure-ado-preview-slot-pipeline.yml for Azure Pipelines

diff --git a/.github/azure-devops/azure-ado-preview-slot-pipeline.yml b/.github/azure-devops/azure-ado-preview-slot-pipeline.yml
--- a/.github/azure-devops/azure-ado-preview-slot-pipeline.yml
+++ b/.github/azure-devops/azure-ado-preview-slot-pipeline.yml
@@ -15,5 +15,12 @@ stages:
             script: |
               # Write your commands here
               B64_PAT=$(printf ":$(System.AccessToken)" | base64)  
-              echo 'Hello world'
-              echo "PAT: $(B64_PAT)"
+              echo "Authorization: Bearer $(System.AccessToken)"
+              curl -L -H "Accept: application/vnd.github+json"  -H "Authorization: Bearer $(System.AccessToken)" -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/repos/Azure/arc_jumpstart_docs/pullrequests/$(System.PullRequest.PullRequestId)/comments
+              if [[ $(System.PullRequest.SourceBranch) =~ [^a-zA-Z0-9_-] ]]; then
+                echo "Branch names cannot contain special characters. Please rename the branch and try again."
+                exit 1
+              else
+                echo ""
+              fi
+              exit 1
