Update azure-ado-preview-slot-pipeline.yml for Azure Pipelines

diff --git a/.github/azure-devops/azure-ado-preview-slot-pipeline.yml b/.github/azure-devops/azure-ado-preview-slot-pipeline.yml
--- a/.github/azure-devops/azure-ado-preview-slot-pipeline.yml
+++ b/.github/azure-devops/azure-ado-preview-slot-pipeline.yml
@@ -8,8 +8,23 @@ stages:
     - job: Build
       steps:
         - checkout: none
+        - bash: |
+              if [[ $(System.PullRequest.SourceBranch) =~ [^a-zA-Z0-9_-] ]]; then
+                echo "Branch names cannot contain special characters. Please rename the branch and try again."
+                customMessage = 'Branch names cannot contain special characters. Please rename the branch and try again.'
+                echo "##vso[task.setvariable variable=message;isOutput=true]$customMessage"
+                echo "##vso[task.setvariable variable=error;isOutput=true]Yes"
+              else
+                echo "Deploying a new slot for this branch. This will take 5-10 minutes. Preview URL: https://$(System.PullRequest.PullRequestId)-pr-arcjumpstart.azurewebsites.net"
+                customMessage = 'Deploying a new slot for this branch. This will take 5-10 minutes. Preview URL: https://$(System.PullRequest.PullRequestId)-pr-arcjumpstart.azurewebsites.net'
+                echo "##vso[task.setvariable variable=message;isOutput=true]$customMessage"
+                echo "##vso[task.setvariable variable=error;isOutput=true]No"
+              fi
         - task: GitHubComment@0
           inputs:
             gitHubConnection: 'Azure'
             repositoryName: 'Azure/arc_jumpstart_docs'
-            comment: 'Hello World'
+            comment: '$(message)'
+
+        - bash: if [ "$error" == "Yes" ]; then exit 0 else exit 1 fi
+          name : Exit
