Update url-checker.yml

diff --git a/.github/workflows/url-checker.yml b/.github/workflows/url-checker.yml
--- a/.github/workflows/url-checker.yml
+++ b/.github/workflows/url-checker.yml
@@ -12,6 +12,8 @@ on:
 jobs:
   url-check:
     runs-on: ubuntu-latest
+    outputs:
+      status: ${{ steps.check-links.outputs.status }}
 
     steps:
     - name: Checkout repository
@@ -31,7 +33,17 @@ jobs:
       run: echo "FORCE_COLOR=1" >> $GITHUB_ENV
       
     - name: Check for broken links
-      run: python scripts/python/url-checker/url-checker.py
+      id: check-links
+      run: |
+        python scripts/python/url-checker/url-checker.py
+        if [ $? -eq 0 ]; then
+          echo "status=success" >> $GITHUB_OUTPUT
+          echo "No broken links found!"
+        else
+          echo "status=failure" >> $GITHUB_OUTPUT
+          echo "Broken links were found!"
+        fi
+      continue-on-error: true
 
     - name: Upload log file
       uses: actions/upload-artifact@v4
@@ -41,3 +53,23 @@ jobs:
 
     - name: Clean up environment
       run: rm -rf scripts/python/url-checker/__pycache__
+
+    - name: Create status badge
+      run: |
+        if [ "${{ steps.check-links.outputs.status }}" == "success" ]; then
+          echo "STATUS_BADGE=passing" >> $GITHUB_ENV
+          echo "STATUS_COLOR=brightgreen" >> $GITHUB_ENV
+        else
+          echo "STATUS_BADGE=failing" >> $GITHUB_ENV
+          echo "STATUS_COLOR=red" >> $GITHUB_ENV
+        fi
+        
+    - name: Update status badge
+      uses: schneegans/dynamic-badges-action@v1.6.0
+      with:
+        auth: ${{ secrets.GIST_SECRET }}
+        gistID: GIST_ID_FOR_BADGE
+        filename: url-checker-status.json
+        label: links
+        message: ${{ env.STATUS_BADGE }}
+        color: ${{ env.STATUS_COLOR }}
